### ISSUE TITLE
Fix : Improve Storage Functionaliy 

### ISSUE THREAD

**Issue by Rhythm-chicmicstudios** [sahil-animesh/angular-16-boilerplate#3]
# Issue
We Should take storage type in the setItemStorage Function () rather than defining it to the env file, by doing so we can make it dynamic for the different condtions and same case for getFromStorage() 

## Remove this ternary operator
~~environment.storageType === STORAGE_TYPE.LOCAL_STORAGE ? localStorage.setItem(key,data) : sessionStorage.setItem(key,data);~~
and take additional Parameter

![image](https://github.com/sahil-animesh/angular-16-boilerplate/assets/125264783/59c1c827-dee8-41a3-ad37-5f19dd1be085)

**Comment by sahil-animesh** [comment]
this is done because we will access this property from enviroment , which defines that which storage type we are going to use such as local storage and session storage
